# Generated by Django 4.0.4 on 2022-05-27 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='seller_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
