# Generated by Django 4.0.4 on 2022-05-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_item_seller_id'),
        ('accounts', '0002_alter_myuser_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item', to_field='seller_id'),
        ),
    ]
