# Generated by Django 4.0.4 on 2022-05-28 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='seller_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
