# Generated by Django 4.0.4 on 2022-05-27 12:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
                ('featured', models.ImageField(upload_to='featured/')),
                ('sold', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics Instruments'), ('furniture', 'Furniture'), ('apparels', 'Apparels'), ('other', 'Other')], max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='seller_id')),
            ],
        ),
    ]
