# Generated by Django 4.0.4 on 2022-06-06 13:18

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
                ('featured', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('sold', models.BooleanField(default=False)),
                ('seller_id', models.UUIDField()),
                ('category', models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics Instruments'), ('furniture', 'Furniture'), ('apparels', 'Apparels'), ('other', 'Other')], max_length=50)),
                ('bought', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
        ),
    ]
