# Generated by Django 4.0.4 on 2022-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bought',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
