# Generated by Django 4.0.4 on 2022-05-28 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
