# Generated by Django 4.0.4 on 2022-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller_id',
            field=models.UUIDField(),
        ),
    ]
