# Generated by Django 4.0.4 on 2022-05-28 21:00

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_item_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemImage', models.ImageField(upload_to=products.models.get_path, verbose_name='Image')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
        ),
    ]
